name: build
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libtool meson ninja-build pkg-config libcapstone-dev device-tree-compiler libglib2.0-dev gnutls-bin libjpeg-turbo8-dev libpng-dev libslirp-dev libssh-dev libusb-1.0-0-dev liblzo2-dev libncurses5-dev libpixman-1-dev libsnappy-dev vde2 zstd libgnutls28-dev libgmp10 libgmp3-dev lzfse liblzfse-dev
      - name: Build nettle 3.10.1
        run: |
          wget https://ftp.gnu.org/gnu/nettle/nettle-3.10.1.tar.gz
          tar -xvf nettle-3.10.1.tar.gz
          cd nettle-3.10.1
          ./configure
          make -j$(nproc)
          sudo make install
      - name: Build
        run: |
          mkdir build
          cd build
          PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig ../configure --target-list=aarch64-softmmu,x86_64-softmmu --enable-capstone --enable-slirp --enable-lzfse --enable-nettle --enable-gnutls --disable-werror
          make -j$(nproc)
      - name: Install
        run: |
          cd build
          make DESTDIR=$GITHUB_WORKSPACE/bin/ install
      - name: Publish binaries
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: ${{ github.workspace }}/bin/

  
